name: Publish

on:
  release:
    types: [published]

jobs:
  getinfo:
    runs-on: ubuntu-latest
    outputs:
      npmtag: ${{ steps.data.outputs.npmtag }}
      websites3bucket: ${{ steps.data.outputs.websites3bucket }}
    steps:
      - uses: actions/checkout@v2
      - run: npm i
        working-directory: ./publish
      - run: node publish/information/index.js
        id: data

  publish-npm:
    needs:
      - getinfo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: node publish/copy-readme.js
      - run: lerna publish from-package --dist-tag $TAG --yes --no-git-tag-version --no-push --no-verify-access --no-git-reset
        env:
          TAG: ${{ needs.getinfo.outputs.npmtag }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

